/** @type {import('tailwindcss').Config} */

module.exports = {
  future: {
    hoverOnlyWhenSupported: true
  },
  darkMode: 'selector',
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    fontFamily: {
      sans: ['Arial', 'Helvetica Neue',  'Untitled Sans', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Noto Sans', 'sans-serif', 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'],
      serif: ['Times New Roman', 'Times', 'Untitled Serif',  'Georgia', 'Cambria', 'serif'],
      mono: ['Berkeley Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'Liberation Mono', 'Courier New', 'monospace'],
    },
    extend: {
      gap: {
        0: '0',
        5: '5px',
        10: '10px',
        15: '15px',
        20: '20px',
        25: '25px',
        30: '30px',
      },
      margin: {
        0: '0',
        5: '5px',
        10: '10px',
        15: '15px',
        20: '20px',
        25: '25px',
        30: '30px',
      },
      padding: {
        0: '0',
        5: '5px',
        10: '10px',
        15: '15px',
        20: '20px',
        25: '25px',
        30: '30px',
      },
      leading: {
        0: '0',
        5: '5px',
        10: '10px',
        15: '15px',
        20: '20px',
        25: '25px',
        30: '30px',
      },
      fontSize: {
        DEFAULT: ['16px', '24px'],
        12: ['12px', '15px'],
        20: ['19px', '20px'],
        24: ['24px', '25px'],
        30: ['27px', '30px'],
      },
      colors: {
        gray: {
          150: "#E6E9ED",
          // 200: "#DBDEE6",
        },
        green: '#23FF27',
        pink: '#eb47ca',
        neutral: {
          50: '#fcfcfc',
          100: '#F5F5F5',
          150: '#f0f0f0',
          200: '#ececec',
          250: '#E6E6E6',
          300: '#ccc',
          400: '#B3B3B3',
          490: '#7D7D7D',
          500: '#8B8B8B',
          700: '#4B4B4B',
          750: '#363636',
          800: '#363636',
          900: '#161616',
          950: '#060606'
        }
      },
      screens: {
        xs: '425px',
        lg: '1024px',
        '2xl': '1600px',
        '3xl': '1900px',
      },
      maxWidth: {
        '2xl': '1480px',
      },
      boxShadow: {
        '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
      },
      gridTemplateColumns: {
        '16': 'repeat(16, minmax(0, 1fr))',
      },
      gridColumn: {
        'span-13': 'span 13 / span 13',
        'span-14': 'span 14 / span 14',
      },
      boxShadow: {
        'sub-pixel-black': 'inset 0 0.5px 0 0 rgba(0, 0, 0, 1)',
        'sub-pixel-white': 'inset 0 0.5px 0 0 rgba(255, 255, 255, 1)',
      },
    }
  },
  variants: {
    borderColor: ['group-hover', 'group-focus'],
    scale: ['group-hover', 'group-focus'],
    shadow: ['group-hover']
  },
  plugins: [
    require('@tailwindcss/typography')
  ],
  safelist: [
    "col-span-1",
    "col-span-2",
    "col-span-3",
    "col-span-4",
    "col-span-5",
    "col-span-6",
    "col-span-7",
    "col-span-8",
    "col-span-9",
    "col-span-10",
    "col-span-11",
    "col-span-12",
    "col-span-13",
    "col-span-14",
    "col-span-15",
    "col-span-16",
    "sm:col-span-1",
    "sm:col-span-2",
    "sm:col-span-3",
    "sm:col-span-4",
    "sm:col-span-5",
    "sm:col-span-6",
    "sm:col-span-7",
    "sm:col-span-8",
    "sm:col-span-9",
    "sm:col-span-10",
    "sm:col-span-11",
    "sm:col-span-12",
    "sm:col-span-13",
    "sm:col-span-14",
    "sm:col-span-15",
    "sm:col-span-16",
    "md:col-span-1",
    "md:col-span-2",
    "md:col-span-3",
    "md:col-span-4",
    "md:col-span-5",
    "md:col-span-6",
    "md:col-span-7",
    "md:col-span-8",
    "md:col-span-9",
    "md:col-span-10",
    "md:col-span-11",
    "md:col-span-12",
    "md:col-span-13",
    "md:col-span-14",
    "md:col-span-15",
    "md:col-span-16",
    "lg:col-span-1",
    "lg:col-span-2",
    "lg:col-span-3",
    "lg:col-span-4",
    "lg:col-span-5",
    "lg:col-span-6",
    "lg:col-span-7",
    "lg:col-span-8",
    "lg:col-span-9",
    "lg:col-span-10",
    "lg:col-span-11",
    "lg:col-span-12",
    "lg:col-span-13",
    "lg:col-span-14",
    "lg:col-span-15",
    "lg:col-span-16",
    "xl:col-span-1",
    "xl:col-span-2",
    "xl:col-span-3",
    "xl:col-span-4",
    "xl:col-span-5",
    "xl:col-span-6",
    "xl:col-span-7",
    "xl:col-span-8",
    "xl:col-span-9",
    "xl:col-span-10",
    "xl:col-span-11",
    "xl:col-span-12",
    "xl:col-span-13",
    "xl:col-span-14",
    "xl:col-span-15",
    "xl:col-span-16",
    "col-start-1",
    "col-start-2",
    "col-start-3",
    "col-start-4",
    "col-start-5",
    "col-start-6",
    "col-start-7",
    "col-start-8",
    "col-start-9",
    "col-start-10",
    "col-start-11",
    "col-start-12",
    "col-start-13",
    "col-start-14",
    "col-start-15",
    "col-start-16",
    "sm:col-start-1",
    "sm:col-start-2",
    "sm:col-start-3",
    "sm:col-start-4",
    "sm:col-start-5",
    "sm:col-start-6",
    "sm:col-start-7",
    "sm:col-start-8",
    "sm:col-start-9",
    "sm:col-start-10",
    "sm:col-start-11",
    "sm:col-start-12",
    "sm:col-start-13",
    "sm:col-start-14",
    "sm:col-start-15",
    "sm:col-start-16",
    "md:col-start-1",
    "md:col-start-2",
    "md:col-start-3",
    "md:col-start-4",
    "md:col-start-5",
    "md:col-start-6",
    "md:col-start-7",
    "md:col-start-8",
    "md:col-start-9",
    "md:col-start-10",
    "md:col-start-11",
    "md:col-start-12",
    "md:col-start-13",
    "md:col-start-14",
    "md:col-start-15",
    "md:col-start-16",
    "lg:col-start-1",
    "lg:col-start-2",
    "lg:col-start-3",
    "lg:col-start-4",
    "lg:col-start-5",
    "lg:col-start-6",
    "lg:col-start-7",
    "lg:col-start-8",
    "lg:col-start-9",
    "lg:col-start-10",
    "lg:col-start-11",
    "lg:col-start-12",
    "lg:col-start-13",
    "lg:col-start-14",
    "lg:col-start-15",
    "lg:col-start-16",
    "xl:col-start-1",
    "xl:col-start-2",
    "xl:col-start-3",
    "xl:col-start-4",
    "xl:col-start-5",
    "xl:col-start-6",
    "xl:col-start-7",
    "xl:col-start-8",
    "xl:col-start-9",
    "xl:col-start-10",
    "xl:col-start-11",
    "xl:col-start-12",
    "xl:col-start-13",
    "xl:col-start-14",
    "xl:col-start-15",
    "xl:col-start-16",
    "col-end-1",
    "col-end-2",
    "col-end-3",
    "col-end-4",
    "col-end-5",
    "col-end-6",
    "col-end-7",
    "col-end-8",
    "col-end-9",
    "col-end-10",
    "col-end-11",
    "col-end-12",
    "col-end-13",
    "col-end-14",
    "col-end-15",
    "col-end-16",
    "sm:col-end-1",
    "sm:col-end-2",
    "sm:col-end-3",
    "sm:col-end-4",
    "sm:col-end-5",
    "sm:col-end-6",
    "sm:col-end-7",
    "sm:col-end-8",
    "sm:col-end-9",
    "sm:col-end-10",
    "sm:col-end-11",
    "sm:col-end-12",
    "sm:col-end-13",
    "sm:col-end-14",
    "sm:col-end-15",
    "sm:col-end-16",
    "md:col-end-1",
    "md:col-end-2",
    "md:col-end-3",
    "md:col-end-4",
    "md:col-end-5",
    "md:col-end-6",
    "md:col-end-7",
    "md:col-end-8",
    "md:col-end-9",
    "md:col-end-10",
    "md:col-end-11",
    "md:col-end-12",
    "md:col-end-13",
    "md:col-end-14",
    "md:col-end-15",
    "md:col-end-16",
    "lg:col-end-1",
    "lg:col-end-2",
    "lg:col-end-3",
    "lg:col-end-4",
    "lg:col-end-5",
    "lg:col-end-6",
    "lg:col-end-7",
    "lg:col-end-8",
    "lg:col-end-9",
    "lg:col-end-10",
    "lg:col-end-11",
    "lg:col-end-12",
    "lg:col-end-13",
    "lg:col-end-14",
    "lg:col-end-15",
    "lg:col-end-16",
    "xl:col-end-1",
    "xl:col-end-2",
    "xl:col-end-3",
    "xl:col-end-4",
    "xl:col-end-5",
    "xl:col-end-6",
    "xl:col-end-7",
    "xl:col-end-8",
    "xl:col-end-9",
    "xl:col-end-10",
    "xl:col-end-11",
    "xl:col-end-12",
    "xl:col-end-13",
    "xl:col-end-14",
    "xl:col-end-15",
    "xl:col-end-16",
    "-mx-15",
    "mx-0",
    "sm:-mx-15",
    "sm:mx-0",
    "md:-mx-15",
    "md:mx-0",
    "lg:-mx-15",
    "lg:mx-0",
    "xl:-mx-15",
    "xl:mx-0",
    "px-15",
    "px-0",
    "sm:px-15",
    "sm:px-0",
    "md:px-15",
    "md:px-0",
    "lg:px-15",
    "lg:px-0",
    "xl:px-15",
    "xl:px-0",
  ],
}
